/** Canonical languages for provider registration and search filters. */
export const PROVIDER_REGISTRATION_LANGUAGES = [
  "Assamese",
  "Bengali",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Marathi",
  "Malayalam",
  "Oriya",
  "Punjabi",
  "Sanskrit",
  "Tamil",
  "Telugu",
  "Urdu",
  "Sindhi",
  "Konkani",
  "Nepali",
  "Manipuri",
  "Bodo",
  "Dogri",
  "Maithili",
  "Santhali",
  "English",
];
