name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "connected"

            cd ~/providers || git clone https://github.com/ServEase-Innovations/providers.git && cd providers

            git pull origin main

            docker rm -f providers-api || true

            docker build -t providers-api .

            docker run -d \
              -p 4000:4000 \
              --env-file .env.prod \
              --name providers-api \
              --restart always \
              providers-api
